#!/usr/bin/env python3
#written by TDB to run the fungalOTU pipeline
#this script checks the metadata file to make sure that it's all in working order

################################################
#imports
import argparse
import Classify_Sanger_OTUs_definitions_module as OTU
import pprint
import sys
from datetime import datetime
import os

################################################
#definitions
def parse_args():
	parser = argparse.ArgumentParser(description="Run the MycorrhizaTracer pipeline to classify Sanger sequences into OTUs")
	#general arguments
	parser.add_argument("-m", "--metadata", type=str, required=False, default = "None", help="Path to the metadata file. Default is a test set of 96 samples at %(default)s.")
	parser.add_argument("-o", "--output_dir", type=str, required=False, default="./TEST_OUTPUT/", help="Directory to store output files. Default is %(default)s")
	parser.add_argument("-p", "--prefix", type=str, required=False, default="", help="Prefix for sequencing files. Convenient if sequencing files are on an external HD as this allows you to set the mountpoint. Default is %(default)s")
	parser.add_argument("-d", "--dirDepth", type=int, default=0, help="Set to make subdirs for consensus sequences to deal with having too many files in a single dir. Default = 0 (no subdirs)")
	parser.add_argument("--cpus", type=int, default=1, help="Number of CPUs to use for parallel processing. Default is %(default)s. Set to 0 to use all available CPUs. Used for blast and vsearch clustering.")
	parser.add_argument("-f", "--outputFile", type=str, default = "Sanger_Output.csv", help="The file name for the data output file to be written. These has all data generated by the pipeline and is the place you should look. It will appear in the directory specified by --output_dir . Tab-delimited. Default = %(default)s")
	parser.add_argument("--resume", action="store_true", help="Resume the pipeline from where it left off. This will skip steps that have already been completed and will not overwrite existing files. Default is False, meaning it will make or overwrite all files. Use with caution; it's always safest to take the time and overwrite all previous files as this does not anticipate downstream effects.")	
	
	#quality trimming and concensus generation arguments
	parser.add_argument("-q", "--qual", type=int, default=20, help="Minimum PHRED quality score for sequence quality trimming. Default is %(default)s. This is used during the quality trimming of the raw chromatograms where a sliding window will be applied and the bases of any region whose window drops below this threshold will be trimmed. Setting it higher is more stringent and a reasonable range is between 15 and 40.")
	parser.add_argument("--window_size", type=int, default=5, help="Size of the sliding window for read trimming based on peak height. Default is %(default)s. This is used to determine how many bases to consider when calculating the average quality score for trimming.")
	parser.add_argument("--stddev_cutoff", type=float, default=0.2, help="Standard deviation cutoff for read trimming based on peak height. Default is %(default)s. This is used to determine how many standard deviations below the mean quality score a base must be to be considered low peak height and trimmed: threshold = mean - (SD * stddev_cutoff). Setting it lower is more stringent (as it makes the cutoff threshold higher because fewer SDs are substracted from the mean) and a reasonable range is probably between 0.0 and about 2.0 maybe. I wouldn't go negative.")
	parser.add_argument("--min_read_len", type=int, default = 100, help="The minimum sequence length for a sequence to be fed into the aligner. This filter is applied AFTER the quality and peak-height trimmers.Default is %(default)s. ")
	parser.add_argument("--manual_consensus_file", type=str, required=False, default=None, help="Path to a metadata file containing manually curated consensus sequences to use. This needs to be in the same format as the standard metadata, but contain *.fq or *.fa file paths instead of *.ab1 paths (only include a consensus in the forward column for each gene). Any sequence*sample present in this file will replace the default consensus generated from *ab1 files. Default is %(default)s")

	#sequence classification arguments
	parser.add_argument("--onlyITS", action="store_true", help="Run only the fungal ITS classification step, skipping the other two plant amplicons (ITS2 and RBCL)")
	parser.add_argument("--species_list_ITS", type=str, required=False, default=None, help="Path to the species list file for ITS. Default is %(default)s")
	parser.add_argument("--species_list_ITS2", type=str, required=False, default=None, help="Path to the species list file for ITS2. Default is %(default)s")
	parser.add_argument("--species_list_RBCL", type=str, required=False, default=None, help="Path to the species list file for RBCL. Default is %(default)s")
	parser.add_argument("--ITS_db", type=str, required=True, help="Path to the BLASTN database for ITS sequences.")
	parser.add_argument("--ITS2_db", type=str, required=True, help="Path to the BLASTN database for ITS2 sequences.")
	parser.add_argument("--RBCL_db", type=str, required=True, help="Path to the BLASTN database for RBCL sequences.")
	parser.add_argument("--minMatchLength", type=int, default=50, help="Minimum match length for BLASTN classification. Default is %(default)s. This is used to filter out short matches that may not be reliable.")
	parser.add_argument("--minSCOV", type=float, default=0.3, help="Minimum subject coverage for BLASTN classification. Default is %(default)s. This is used to filter out matches that do not cover a sufficient portion of the query sequence. Best to set this very high like 0.98 or 0.99 if your sequences are longer than the database (i.e.: PacBio reads vs UNITE). Set it close to the ratio of qlen/slen (i.e.: 0) if your database sequences are chromosome-long. Maybe leave it alone for Sanger reads that are about the same as the database (~500bps).")
	parser.add_argument("--minQCOV", type=float, default=0.3, help="Minimum query coverage for BLASTN classification. Default is %(default)s. This is used to filter out matches that do not cover a sufficient portion of the query sequence. If your query sequences are longer than the database set this fairly low, perhaps a bit less than the ratio of slen/qlen. If the database sequences are longer - especially if they are MUCH longer - then set it closer to 1. Default is probably fine if your sequences are about the same length as the database (i.e.: Sanger reads vs UNITE)")
	parser.add_argument("--pidentDiff", type=float, required=False, default=0.5,  help="The differential between the best hit (after --minMatchLength is applied) and the other hits to consider. If the best hit has a pident of 97.5 and this is set to 0.5, then all hits with pident > 97.0 will be considered and compared. For the fungal work with UNITE 0.5-1.5 all seem fine. If you set this to 0, it will simply take the hit with the highest Evalue which will give you the cleanest dataset at the cost of hiding all uncertainty, so treat that with the greatest of caution. Default = %(default)s")
	parser.add_argument("--no_Incertae_Sedis", action='store_true', default=False, help="Use this to force the best hit to be one without incertae sedis. Filter is applied after the minMatchLen, minSCOV and minQCOV filters, but before hits below max_pident minus differential are removed. If all hits are Incertae Sedis, then Incertae Sedis is returned. Including this should help FUNGuild do it's annotation, but may cause classifications to be less rigorous. This *could* be very dangerous if all 'real' hits are incertae sedis, and the only non-incertae sedis hit is spurious. I have no idea how often that occurs. If you want to use this flag, I suggest you run it with and without and compare the two methods.")
	parser.add_argument("--adjustPidents", action='store_true', default=False, help="Add this flag to discount Pidents by any non-matching, but overlapping sequence regions. This is essentially forcing a global alignment. Default = %(default)s")
	parser.add_argument("--min_pident_species", type=float, required=False, default=97.0, help="The minimum pident to classify something as a species.  Default = %(default)s")
	parser.add_argument("--min_pident_genus",   type=float, required=False, default=94.0, help="The minimum pident to classify something as a genus.  Default = %(default)s")
	parser.add_argument("--min_pident_family",  type=float, required=False, default=90.0, help="The minimum pident to classify something as a family.  Default = %(default)s")
	parser.add_argument("--min_pident_order",   type=float, required=False, default=85.0, help="The minimum pident to classify something as an order.  Default = %(default)s")
	parser.add_argument("--min_pident_class",   type=float, required=False, default=80.0, help="The minimum pident to classify something as a class.  Default = %(default)s")
	parser.add_argument("--min_pident_phylum",  type=float, required=False, default=80.0, help="The minimum pident to classify something as a phylum.  Default = %(default)s")
	parser.add_argument("--min_pident_kingdom", type=float, required=False, default=80.0, help="The minimum pident to classify something as a kingdom.  Default = %(default)s")
	
	#clustering arguments
	parser.add_argument("--minSeqLengthForCluster", type=int, default=300, help="Minimum sequence length for clustering. Default is %(default)s. This is used to filter out short sequences that may not be reliable for clustering.")
	parser.add_argument("--minAverageQualityForCluster", type=int, default=20, help="Minimum average quality score for consensus sequences to be included in clustering. Default is %(default)s. This is used to filter out low quality consensus sequences that may not be reliable for clustering.")
	parser.add_argument("--percentIdentityForCluster", type=float, default=97.0, help="Percent identity for clustering sequences. Default is %(default)s. This is used to determine the similarity threshold for clustering sequences. Set this to 0.97 for 97 percent identity, which is a common threshold for clustering ITS sequences.")
	parser.add_argument("--cluster_plants_too", action="store_true", help="Cluster plant sequences (ITS2 and RBCL) as well as fungal sequences (ITS). Default is False. If this is set, then the clustering will be performed on all three genes.")
	
	#salvaging arguments
	parser.add_argument("-s", "--salvage", action="store_true", help="Run the salvage step to recover low quality sequences")
	parser.add_argument("--min_read_len_salvage", type=int, default = 150, help="The minimum sequence length for a sequence to be considered for salvaging. Default is %(default)s.")
	
	#funguild arguments
	parser.add_argument("-F", "--run_funguild", action="store_true", help="Run FUNGuild on the classified sequences. Default is False.")
	parser.add_argument("--FUNGuild_executable", type=str, required=False, default = "", help="Location of the FUNGuild executable on your computer. The executable will be titled something like Guilds_v1.1.py and if it exists in your $PATH you can omit this option. Default = %(default)s")

	#summary arguments

	#logging arguments
	parser.add_argument("--verbose", action="store_true", help="Print verbose output to stderr. Default is False.")
	parser.add_argument("--sequence_stats", action="store_true", help="Print sequence statistics to SequenceStats.csv in output dir. Default is False. This will print out the sequence ID, length, quality for each chromatogram as they are processed.")
	#troublseshooting arguments
	parser.add_argument("--troubleshooting", action="store_true", help="Run the pipeline in troubleshooting mode. This will print additional information to stderr and may create additional output files for debugging purposes. Default is False.")
	parser.add_argument("--firstNsamples", type=int, default=0, help="Run the pipeline on only the first N samples in the metadata file. This is useful for testing and debugging. but should never be used for the final analysis. Default is %(default)s, which means all samples will be processed. Set to 0 to process all samples.")
	return parser.parse_args()

def main(): 
	args = parse_args()
	
	#get runtime for logging
	start_time = datetime.now().strftime("%Y-%m-%d_%H%M")

	#build output directory structure
	OTU.make_output_dirs(args.output_dir)

	SS_FH = None
	if args.sequence_stats:
		sequence_stats_file = os.path.join(args.output_dir, "SequenceStats.txt")
		SS_FH = open(sequence_stats_file, "w")
		print("Sample_ID	Gene	Direction	Sequence_Length	Average_Quality", file=SS_FH)  # Header for sequence stats file


	#load metadata
	MetaDict = OTU.load_metadata(args)
	
	#[pprint.pprint(MetaDict[Sample_ID]["Metadata"]["SalvageGroup"]) for Sample_ID in MetaDict]  # Print metadata for each sample
	#len(set(MetaDict[Sample_ID]["Metadata"]["SalvageGroup"] for Sample_ID in MetaDict))
	#input("wait")
		
	#create fastq for each sample from ab1 files or scf files then make those into consensus sequences 
	MetaDict = OTU.create_fastq_from_ab1(MetaDict, args, SS_FH)
	#input("create fastq done, hold for sec")
	MetaDict = OTU.make_consensus_fastq(MetaDict, args)
	#pprint.pprint(MetaDict["A01"]["ITS"]["Seqs"])
	#pprint.pprint(MetaDict["A04"]["ITS"]["Seqs"])
	#input("make consensus done, hold for sec")
	#for Sample_ID in MetaDict:
	#	if MetaDict[Sample_ID]["ITS"]["Seqs"]["Cons"]["nSeqs"] == 1:
	#		print(f"Sample ID: {Sample_ID}")
	#		pprint.pprint(MetaDict[Sample_ID]["ITS"]["Seqs"])

	
	#classify sequences (clusters?) with blastn
	MetaDict = OTU.classify_seqs_blastn(MetaDict, args)
	#input("make blasts done, hold for sec")
	#for S in MetaDict:
	#	print(S)
	#	pprint.pprint(MetaDict[S]["Classifications"])
	#input("hold for sec")
	#pprint.pprint(MetaDict)
	
	#cluster sequences with vsearch
	MetaDict = OTU.cluster_seqs_vsearch(MetaDict, args)
	#input("make clustesr done, hold for sec")

	#salvage lowQ sequences
	if args.salvage:
		MetaDict = OTU.salvage_lowQ_seqs(MetaDict, args)
		#input("make salvaging done, hold for sec")

	#run funguild
	if args.run_funguild:
		MetaDict = OTU.run_funguild(MetaDict, args)
	
	
	#write the summary file and summary stats
	#pprint.pprint(MetaDict)
	#pprint.pprint(MetaDict["Sample_2282"])
	#input("hold for sec")
	#pprint.pprint(MetaDict["N23_3"])
	#pprint.pprint(MetaDict["N23_5"])

	#do summaries
	OTU.print_final_summary_Stats(MetaDict, args, sys.stderr, " ".join(sys.argv))
	logfile = os.path.join(args.output_dir, "Sanger_Summary."+start_time+".txt")
	with open(logfile, "w") as logFH:
		OTU.print_final_summary_Stats(MetaDict, args, logFH, " ".join(sys.argv))

	#pprint.pprint(MetaDict["N1_10"])

	OTU.write_data_summary_file(MetaDict, args, " ".join(sys.argv), start_time)


	#input("wait")
	if args.sequence_stats:
		SS_FH.close()
		OTU.write_sequence_stats(MetaDict, args, sequence_stats_file)


if __name__ == "__main__":
	main()

